
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "ID NUMBER PRINTprogram : statementsstatements : statements statement\n                  | statement statement : assignment\n                  | expr\n                  | printassignment : ID '=' exprexpr : expr '+' term\n            | expr '-' term\n            | termterm : term '*' factor\n            | term '/' factor\n            | factorfactor : ID\n              | NUMBER\n              | '(' expr ')' exprs : exprs ',' expr\n             | exprprint : PRINT '(' exprs ')'\n              | PRINT '(' ')' "
    
_lr_action_items = {'ID':([0,2,3,4,5,6,7,8,10,11,12,13,14,15,16,17,18,19,21,22,23,24,25,26,28,30,31,32,],[7,7,-3,-4,-5,-6,-14,-10,21,-13,-15,-2,21,21,21,21,21,21,-14,-8,-9,-7,-11,-12,-20,-16,-19,21,]),'PRINT':([0,2,3,4,5,6,7,8,11,12,13,21,22,23,24,25,26,28,30,31,],[9,9,-3,-4,-5,-6,-14,-10,-13,-15,-2,-14,-8,-9,-7,-11,-12,-20,-16,-19,]),'NUMBER':([0,2,3,4,5,6,7,8,10,11,12,13,14,15,16,17,18,19,21,22,23,24,25,26,28,30,31,32,],[12,12,-3,-4,-5,-6,-14,-10,12,-13,-15,-2,12,12,12,12,12,12,-14,-8,-9,-7,-11,-12,-20,-16,-19,12,]),'(':([0,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,21,22,23,24,25,26,28,30,31,32,],[10,10,-3,-4,-5,-6,-14,-10,19,10,-13,-15,-2,10,10,10,10,10,10,-14,-8,-9,-7,-11,-12,-20,-16,-19,10,]),'$end':([1,2,3,4,5,6,7,8,11,12,13,21,22,23,24,25,26,28,30,31,],[0,-1,-3,-4,-5,-6,-14,-10,-13,-15,-2,-14,-8,-9,-7,-11,-12,-20,-16,-19,]),'+':([5,7,8,11,12,20,21,22,23,24,25,26,29,30,33,],[14,-14,-10,-13,-15,14,-14,-8,-9,14,-11,-12,14,-16,14,]),'-':([5,7,8,11,12,20,21,22,23,24,25,26,29,30,33,],[15,-14,-10,-13,-15,15,-14,-8,-9,15,-11,-12,15,-16,15,]),'=':([7,],[16,]),'*':([7,8,11,12,21,22,23,25,26,30,],[-14,17,-13,-15,-14,17,17,-11,-12,-16,]),'/':([7,8,11,12,21,22,23,25,26,30,],[-14,18,-13,-15,-14,18,18,-11,-12,-16,]),')':([8,11,12,19,20,21,22,23,25,26,27,29,30,33,],[-10,-13,-15,28,30,-14,-8,-9,-11,-12,31,-18,-16,-17,]),',':([8,11,12,21,22,23,25,26,27,29,30,33,],[-10,-13,-15,-14,-8,-9,-11,-12,32,-18,-16,-17,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'statements':([0,],[2,]),'statement':([0,2,],[3,13,]),'assignment':([0,2,],[4,4,]),'expr':([0,2,10,16,19,32,],[5,5,20,24,29,33,]),'print':([0,2,],[6,6,]),'term':([0,2,10,14,15,16,19,32,],[8,8,8,22,23,8,8,8,]),'factor':([0,2,10,14,15,16,17,18,19,32,],[11,11,11,11,11,11,25,26,11,11,]),'exprs':([19,],[27,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> statements','program',1,'p_program','py_yacc.py',24),
  ('statements -> statements statement','statements',2,'p_statements','py_yacc.py',31),
  ('statements -> statement','statements',1,'p_statements','py_yacc.py',32),
  ('statement -> assignment','statement',1,'p_statement','py_yacc.py',43),
  ('statement -> expr','statement',1,'p_statement','py_yacc.py',44),
  ('statement -> print','statement',1,'p_statement','py_yacc.py',45),
  ('assignment -> ID = expr','assignment',3,'p_assignment','py_yacc.py',52),
  ('expr -> expr + term','expr',3,'p_expr','py_yacc.py',61),
  ('expr -> expr - term','expr',3,'p_expr','py_yacc.py',62),
  ('expr -> term','expr',1,'p_expr','py_yacc.py',63),
  ('term -> term * factor','term',3,'p_term','py_yacc.py',75),
  ('term -> term / factor','term',3,'p_term','py_yacc.py',76),
  ('term -> factor','term',1,'p_term','py_yacc.py',77),
  ('factor -> ID','factor',1,'p_factor','py_yacc.py',89),
  ('factor -> NUMBER','factor',1,'p_factor','py_yacc.py',90),
  ('factor -> ( expr )','factor',3,'p_factor','py_yacc.py',91),
  ('exprs -> exprs , expr','exprs',3,'p_exprs','py_yacc.py',106),
  ('exprs -> expr','exprs',1,'p_exprs','py_yacc.py',107),
  ('print -> PRINT ( exprs )','print',4,'p_print','py_yacc.py',119),
  ('print -> PRINT ( )','print',3,'p_print','py_yacc.py',120),
]
